---
# tasks file for app
- name: Show env nanme
  debug:
    msg: "This is {{ env }} env"
- name: Add unit file for app
  become: true
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload-puma
- name: Add config file for puma
  template:
    src: db_config.j2
    dest: /home/ubuntu/db_config
    mode: 0644
    owner: ubuntu
    group: ubuntu
- name: Enable puma
  become: true
  systemd: daemon_reload=yes name=puma enabled=yes
