---
- name : Configure APP host & deply app
  hosts: app-stage
  vars:
    db_host : 51.250.84.102
  tasks:
    - name: Add unit file for app
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload-puma

    - name: Add config file for puma
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: 0644
        owner: ubuntu
        group: ubuntu


    - name: Enable puma
      become: true
      systemd: daemon_reload=yes name=puma enabled=yes


  handlers:
     - name: reload-puma
       become: true
       systemd: name=puma state=restarted
